# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MV Buddies Blog
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
  #Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.


baseurl: "https://blog.mvbuddies.de" # the subpath of your site, e.g. /blog
url: "http://blog.mvbuddies.de" # the base hostname & protocol for your site

#sidebar
default-image: 400x250.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: webjeda

copyright:
   name: MV Buddies
   link: 'https://mvbuddies.de'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

ftp_host: 'ftp.mvbuddies.de' # fill in your website
ftp_dir: '/blog.mvbuddies.de/' # fill in the root of your path to the folder where you want to host the website
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'mvbuddi1'     # fill in your FTP username
ftp_password: '2Qn(Q0ds7YV!h7' # fill in your FTP password
ftp_secure: false              # default false

# Tracker
#analytics: UA-83979019-1

# Comments
disqus: yes
disqus-shortname: mvbuddies

social:
#facebook: http://facebook.com/webjeda
#quora: http://quora.com/sharathdt
twitter: http://twitter.com/@mv_buddies
github: http://github.com/mvbuddies
email: mvbuddies@gmail.com

#facebook like box
fb-like-box: no
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

#Autoren
authors:
      j0nas500:
        name: Jonas K.
        bio: Schüler in MV, Blogger, programmiere und zocke ab und zu. <a href="https://jonas.mvbuddies.de" >Mehr erfahren</a></p>
        #email: mailto:info@dxartist.com
        twitter: https://twitter.com/j0nas500
        github: https://github.com/j0nas500/
        image: https://blog.mvbuddies.de/images/jonas.png


      sampaths:
        name: Sampath Sirimane
        bio: Sampath is a blogger, story and novel writer for a damous daily news paper.
        email: mailto:sirimane@gmail.com
        twitter: https://twitter.com/sirimane
        github: https://github.com/sirimane/
        image: https://blog.mvbuddies.de/images/jonas.png

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
